# Generated by Django 4.2 on 2025-07-26 04:42

from django.db import migrations, models
import django.db.models.deletion
import payslip_generation_system.models.employee


class Migration(migrations.Migration):

    dependencies = [
        ('payslip_generation_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('birthdate', models.DateField()),
                ('address', models.TextField(blank=True, null=True)),
                ('contact', models.CharField(blank=True, max_length=20, null=True)),
                ('attainment', models.CharField(choices=[('High School', 'High School'), ('Vocational', 'Vocational'), ('Post Graduate', 'Post Graduate'), ('College', 'College')], max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('employee_number', models.CharField(max_length=50, unique=True)),
                ('position', models.CharField(max_length=100)),
                ('date_hired', models.DateField(blank=True, null=True)),
                ('division', models.CharField(blank=True, max_length=20, null=True)),
                ('section', models.CharField(blank=True, max_length=20, null=True)),
                ('fund_source', models.CharField(choices=[('regular', 'Regular'), ('prcmo', 'PRCMO'), ('manila_bay', 'Manila Bay')], max_length=20)),
                ('tax_declaration', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('eligibility', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=payslip_generation_system.models.employee.generate_filename)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='payslip_generation_system.employee')),
            ],
        ),
    ]
