# Generated by Django 4.2 on 2025-07-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslip_generation_system', '0002_employee_employeeattachment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='attainment',
            new_name='education',
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
