# Generated by Django 4.2 on 2025-07-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslip_generation_system', '0003_rename_attainment_employee_education_employee_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_number',
            field=models.CharField(max_length=50),
        ),
    ]
