# Generated by Django 4.2 on 2025-07-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslip_generation_system', '0006_adjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='assigned_office',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
