# Generated by Django 4.2 on 2025-07-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslip_generation_system', '0008_alter_employee_assigned_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustment',
            name='cutoff_year',
            field=models.CharField(default=2025, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adjustment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Returned', 'Returned')], max_length=10),
        ),
    ]
