# Generated by Django 4.2 on 2025-07-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslip_generation_system', '0009_adjustment_cutoff_year_alter_adjustment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='has_philhealth',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
