# Generated by Django 4.2 on 2025-08-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslip_generation_system', '0010_employee_has_philhealth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='assigned_office',
            field=models.CharField(blank=True, choices=[('denr_ncr_nec', 'DENR NCR NEC'), ('meo_s', 'MEO SOUTH'), ('meo_e', 'MEO EAST'), ('meo_w', 'MEO WEST'), ('meo_n', 'MEO NORTH')], max_length=100, null=True),
        ),
    ]
