# Generated by Django 4.2 on 2025-08-02 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payslip_generation_system', '0011_alter_employee_assigned_office'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.IntegerField()),
                ('cutoff_month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=20)),
                ('cutoff', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd')], max_length=10)),
                ('cutoff_year', models.CharField(max_length=50)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batchassignment', to='payslip_generation_system.employee')),
            ],
            options={
                'ordering': ['cutoff_year', 'cutoff_month', 'cutoff', 'batch_number'],
                'unique_together': {('employee',)},
            },
        ),
    ]
