# Generated by Django 4.2 on 2025-08-03 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payslip_generation_system', '0012_batchassignment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batchassignment',
            unique_together={('employee', 'cutoff', 'cutoff_month', 'cutoff_year')},
        ),
    ]
