# Generated by Django 4.2 on 2025-08-05 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslip_generation_system', '0013_alter_batchassignment_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustment',
            name='batch_number',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
