# Generated by Django 4.2 on 2025-08-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslip_generation_system', '0014_adjustment_batch_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchassignment',
            options={'ordering': ['cutoff_year', 'cutoff_month', 'cutoff', 'batch_number', 'late_assigned']},
        ),
        migrations.AddField(
            model_name='batchassignment',
            name='late_assigned',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=10, null=True),
        ),
    ]
