# Generated by Django 4.2 on 2025-08-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslip_generation_system', '0015_alter_batchassignment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchassignment',
            options={'ordering': ['cutoff_year', 'cutoff_month', 'cutoff', 'batch_number', 'late_assigned', 'previous_batch']},
        ),
        migrations.AddField(
            model_name='batchassignment',
            name='previous_batch',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
