# Generated by Django 4.2 on 2025-08-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslip_generation_system', '0016_alter_batchassignment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchassignment',
            name='late_assigned',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=10, null=True),
        ),
    ]
