# Generated by Django 4.2 on 2025-08-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslip_generation_system', '0018_returnremark_returnedadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchassignment',
            name='removed',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=10, null=True),
        ),
    ]
