# Generated by Django 4.2 on 2025-08-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslip_generation_system', '0019_batchassignment_removed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchassignment',
            options={'ordering': ['cutoff_year', 'cutoff_month', 'cutoff', 'assigned_office', 'batch_number', 'late_assigned', 'previous_batch']},
        ),
        migrations.AddField(
            model_name='batchassignment',
            name='assigned_office',
            field=models.CharField(blank=True, choices=[('denr_ncr_nec', 'DENR NCR NEC'), ('meo_s', 'MEO SOUTH'), ('meo_e', 'MEO EAST'), ('meo_w', 'MEO WEST'), ('meo_n', 'MEO NORTH')], max_length=100, null=True),
        ),
    ]
