# Generated by Django 4.2 on 2025-08-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslip_generation_system', '0020_alter_batchassignment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustment',
            name='assigned_office',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
