# Generated by Django 4.2 on 2025-08-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslip_generation_system', '0022_returnremark_assigned_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnedadjustment',
            name='assigned_office',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
