# Generated by Django 4.2 on 2025-08-10 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payslip_generation_system', '0023_returnedadjustment_assigned_office'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='returnremark',
            unique_together={('cutoff', 'cutoff_month', 'cutoff_year', 'batch_number', 'assigned_office')},
        ),
    ]
