# Generated by Django 4.2 on 2025-08-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslip_generation_system', '0024_alter_returnremark_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(blank=True, choices=[('COS', 'COS'), ('ER', 'ER')], max_length=100, null=True),
        ),
    ]
