# Generated by Django 4.2 on 2025-08-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslip_generation_system', '0025_employee_employee_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchassignment',
            name='cluster_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
