# Generated by Django 4.2 on 2025-08-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslip_generation_system', '0026_batchassignment_cluster_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchassignment',
            name='cluster_number',
        ),
        migrations.AddField(
            model_name='batchassignment',
            name='cluster_code',
            field=models.CharField(blank=True, default='NO', max_length=10, null=True),
        ),
    ]
