# Generated by Django 4.2 on 2025-08-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslip_generation_system', '0027_remove_batchassignment_cluster_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchassignment',
            name='cluster_code',
            field=models.CharField(blank=True, default='not_set', max_length=10, null=True),
        ),
    ]
