# Generated by Django 4.2 on 2025-08-11 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payslip_generation_system', '0028_alter_batchassignment_cluster_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchassignment',
            name='cluster_code',
        ),
    ]
