# Generated by Django 4.2 on 2025-08-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslip_generation_system', '0030_batchassignment_cluster_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchassignment',
            name='cluster_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
