# Generated by Django 4.2 on 2025-08-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslip_generation_system', '0033_batchassignment_cluster_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchassignment',
            name='cluster_code',
        ),
        migrations.AddField(
            model_name='batchassignment',
            name='cluster_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
