# Generated by Django 4.2 on 2025-08-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslip_generation_system', '0034_remove_batchassignment_cluster_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='cluster_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
