# Generated by Django 4.2 on 2025-08-12 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslip_generation_system', '0035_employee_cluster_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='cluster_number',
            new_name='batch_number',
        ),
        migrations.RemoveField(
            model_name='batchassignment',
            name='cluster_number',
        ),
        migrations.AlterField(
            model_name='adjustment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Returned', 'Returned'), ('Credited', 'Credited')], max_length=10),
        ),
        migrations.AlterField(
            model_name='batchassignment',
            name='assigned_office',
            field=models.CharField(blank=True, choices=[('denr_ncr_nec', 'DENR NCR NEC'), ('denr_ncr_prcmo', 'DENR NCR PRCMO'), ('meo_s', 'MEO SOUTH'), ('meo_e', 'MEO EAST'), ('meo_w', 'MEO WEST'), ('meo_n', 'MEO NORTH')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='assigned_office',
            field=models.CharField(blank=True, choices=[('denr_ncr_nec', 'DENR NCR NEC'), ('denr_ncr_prcmo', 'DENR NCR PRCMO'), ('meo_s', 'MEO SOUTH'), ('meo_e', 'MEO EAST'), ('meo_w', 'MEO WEST'), ('meo_n', 'MEO NORTH')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='returnedadjustment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Returned', 'Returned'), ('Credited', 'Credited')], max_length=10),
        ),
    ]
