# Generated by Django 4.2 on 2025-08-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslip_generation_system', '0037_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='batch_assigned_office',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
