# Generated by Django 4.2 on 2025-08-12 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payslip_generation_system', '0038_batch_batch_assigned_office'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Batch',
        ),
    ]
