# Generated by Django 4.2 on 2025-08-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslip_generation_system', '0040_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('batch_name', 'batch_assigned_office')},
        ),
    ]
